#!/bin/sh
#
# @name Concrete Tilting Quadrotor-H
#
# @type Tilting Multirotor
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN6 motor 7
# @output MAIN6 motor 8
# @output MAIN6 motor 9
# @output MAIN6 motor 10
# @output MAIN6 motor 11
# @output MAIN6 motor 12
#
# @output AUX1 motor 1
# @output AUX2 motor 2
# @output AUX3 motor 3
# @output AUX4 motor 4
#
# @maintainer Michele Marolla <mic.marolla@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 13 #11 Tilting Multirotor

set MAV_TYPE 14 #octorotor (0 is generic)
param set-default MC_PITCH_ON_TILT 1
param set-default CA_TILTING_TYPE 0

#set MIXER generic_tilting_sitl
#set MIXER_AUX generic_tilting_sitl
#set MIXER_FILE etc/mixers-sitl/generic_tilting_sitl.aux.mix
#set MIXER custom

# Set all 8 channels
set PWM_OUT 12345678
set PWM_AUX_OUT 1234
param set-default CA_ROTOR_COUNT 4
param set-default CA_SV_TL_COUNT 2

param set-default CA_ROTOR0_PX 0.265 #M1 CCW
param set-default CA_ROTOR0_PY 0.344
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX 0.265 #M2 CW
param set-default CA_ROTOR1_PY -0.344
param set-default CA_ROTOR1_PZ 0
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX -0.265  #M3 CCW
param set-default CA_ROTOR2_PY -0.344
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX -0.265 #M4 CW
param set-default CA_ROTOR3_PY 0.344
param set-default CA_ROTOR3_PZ 0
param set-default CA_ROTOR3_KM -0.05


param set-default PWM_MAIN_FUNC1 101 #esc
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108
param set-default PWM_MAIN_FUNC9 201 #servo
param set-default PWM_MAIN_FUNC10 202

# Limits for tilting angles
param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL0_MINA -45
param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL1_MINA -45

